micronaut:
  application:
    name: emento
  server:
    port: 80
emento:
  sendgrid:
    apiKey: ${sendgrid.api.key:iamnotasecret}

  cassandra:
    host: ${cassandra.host:localhost}
    password: ${cassandra.account.key:cassandra}
    username: ${cassandra.username:cassandra}
    port: 10350

  queue:
    connectionString: ${service.bus.connection.string:iamnotasecret}
    name: abledenthusiastqueue
